# site settings
title: KI Junker-Latocha
subtitle: Inhaber Brian Junker-Latocha
email: brian@junker-latocha.com
description: Effektiv denken, KI lenken.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Hermann-Steinhäuser-Str. 18 
city: Offenbach am Main
zip_code: 63065
country: Deutschland
phone: 0049 176 444 20427

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  # GitHub: https://github.com/andrewbanchich
  # GitLab:
  # Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  # Instagram:
  LinkedIn: https://www.linkedin.com/in/junker-latocha
  # Twitter: https://twitter.com/andrewbanchich
  # Facebook:
  # Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
